#!/bin/sh /etc/rc.common
# /etc/init.d/openwrt-telebot


USE_PROCD=1
START=95
STOP=01


PROG="/opt/openwrt-telebot/bot/main.py"


start_service() {
procd_open_instance
procd_set_param command "$PROG"
procd_set_param respawn 300 10 5 # 5 restarts in 300s, 10s delay
procd_set_param stdout 1
procd_set_param stderr 1
procd_close_instance
}


stop_service() {
:
}
